stages:
  - build

build:
  stage: build
  image: node:lts-buster
  before_script:
    - apt update
    - apt install default-jdk libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
    - corepack enable
    - corepack prepare pnpm@latest-7 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm build
    - pnpm turbo lint:check test:e2e
  cache:
    key:
      files:
        - pnpm-lock.yaml
      paths:
        - .pnpm-store
